### ISSUE TITLE
Favor usar inputCheckBox

### ISSUE THREAD

**Issue by david-o-rosario1201** [Frailyng/RegistroTecnicos#8]
https://github.com/Frailyng/RegistroTecnicos/blob/0b13d7d1d911f5f1655da83f52494cf4170aa0dd/RegistroTecnicos/Components/Pages/TiposTecnicosPages/Create.razor#L32

**Comment by Frailyng** [comment]
981b6655335ddbe560c547eb400ca3874da21fb9
Uso del InputCheckBox
