### ISSUE TITLE
Favor poner el volver como un link no como un metodo

### ISSUE THREAD

**Issue by Reyx38** [Frailyng/RegistroTecnicos#9]
https://github.com/Frailyng/RegistroTecnicos/blob/8f200bd453ec59f22873b9b1ca3b3cc345c82a74/RegistroTecnicos/Components/Pages/PrioridadesPages/Details.razor#L58-L61

**Comment by Frailyng** [comment]
b464025ff983038d215a345f02c0b4caa0b110ce

Puesto como un link y no por metodo
